steps:
- name: node:14
  entrypoint: npm
  args: ['install', 'typescript']
- name: node:14
  entrypoint: npm
  args: ['install']
  # run webpack prod script to create static files
- name: node:14
  entrypoint: npm
  args: ['run','build']
  env:
    - 'REACT_APP_API_KEY=eyJzb3VsSWQiOiJkZG5hLWd1aWxoZXJtZS1jb3JyZWEtbmV0by0tdGFrZWRhLWVzcGVjaWFsaXMiLCJhdXRoU2VydmVyIjoiaHR0cHM6Ly9kaC5zb3VsbWFjaGluZXMuY2xvdWQvYXBpL2p3dCIsImF1dGhUb2tlbiI6ImFwaWtleV92MV83NTRmMjc0Yy00NzQyLTQzZTEtODQ3Yy05NzQ4ODlmYjY1YzIifQ=='
    - 'REACT_APP_GA_TRACKING_ID=G-G5GWJ2XYRS'
    - 'DISABLE_ESLINT_PLUGIN=true'
    - 'REACT_APP_SESSION_SERVER=dh.soulmachines.cloud'
    - 'REACT_APP_PERSONA_AUTH_MODE=0'
    - 'REACT_APP_ORCHESTRATION_MODE=false'
    - 'GENERATE_SOURCEMAP=false'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"