name: Build & Sync S3

on:
  push:
    branches: ["main"]
  #workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    name: Deploy Front
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Secrets
        env:
          REACT_APP_API_KEY: ${{ secrets.API_KEY_TAKEDA_COPILOT }}
          REACT_APP_TOKEN_URL: ${{ secrets.API_KEY_TAKEDA_COPILOT }}
        run: |
          echo REACT_APP_API_KEY="$REACT_APP_API_KEY" >> env
          echo REACT_APP_TOKEN_URL="$REACT_APP_TOKEN_URL" >> env
          mv env .env

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PRD_AWS_ROLE_TO_ASSUME }}
          role-session-name: githubaction
          aws-region: ${{ secrets.PRD_AWS_DEFAULT_REGION }}

      - name: Sync to s3 bucket
        env:
          AWS_S3_BUCKET: sites.pessoadigital.digitalsolvers.com
          CUSTOMER: takeda-copilot
        run: |
          cp build/index.html build/$CUSTOMER
          aws s3 sync build/ s3://$AWS_S3_BUCKET/takeda-copilot
